@extends('billing.layouts.app')
@section('title', $batch->period_label.' Payroll')
@section('content')
<div class="mx-auto max-w-7xl space-y-6">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-xs font-bold uppercase tracking-widest text-gray-400">Payroll batch</p><h1 class="text-2xl font-extrabold">{{ $batch->period_label }}</h1><p class="text-sm text-gray-500">Revision {{ $batch->revision }} · {{ $batch->original_filename }} · uploaded {{ $batch->uploaded_at?->format('M d, Y h:i A') }}</p></div><div class="flex flex-wrap gap-2"><a href="{{ route('admin.billing.payroll.index') }}" class="rounded-xl border px-4 py-2.5 text-sm font-extrabold text-gray-700">Back</a><a target="_blank" href="{{ route('admin.billing.payroll.batch.print', $batch) }}" class="rounded-xl border border-[#1a5632] px-4 py-2.5 text-sm font-extrabold text-[#1a5632]">Print All</a>@can('billing.create')<a href="{{ route('admin.billing.payroll.upload') }}" class="rounded-xl bg-amber-600 px-4 py-2.5 text-sm font-extrabold text-white">Re-upload Month</a>@endcan</div></div>
    @if(session('success'))<div class="rounded-xl border border-green-200 bg-green-50 px-5 py-3 text-sm font-bold text-green-800">{{ session('success') }}</div>@endif
    <div class="grid gap-4 sm:grid-cols-3"><div class="rounded-2xl border bg-white p-5"><p class="text-xs font-bold uppercase text-gray-400">Employees</p><p class="mt-2 text-2xl font-black">{{ $batch->row_count }}</p></div><div class="rounded-2xl border bg-white p-5"><p class="text-xs font-bold uppercase text-gray-400">Net Payroll</p><p class="mt-2 text-2xl font-black text-[#1a5632]">Rs. {{ number_format($batch->total_net_amount,2) }}</p></div><div class="rounded-2xl border bg-white p-5"><p class="text-xs font-bold uppercase text-gray-400">Uploaded by</p><p class="mt-2 text-lg font-black">{{ $batch->uploader?->name ?? 'System' }}</p></div></div>
    <div class="overflow-hidden rounded-2xl border bg-white shadow-sm"><div class="overflow-x-auto"><table class="w-full text-left"><thead class="bg-gray-50 text-xs font-bold uppercase tracking-widest text-gray-500"><tr><th class="px-5 py-4">Staff ID</th><th class="px-5 py-4">Employee</th><th class="px-5 py-4">Account / PAN</th><th class="px-5 py-4 text-right">Gross before tax</th><th class="px-5 py-4 text-right">Tax</th><th class="px-5 py-4 text-right">Net</th><th class="px-5 py-4 text-right">Payslip</th></tr></thead><tbody class="divide-y">
    @foreach($batch->payslips as $payslip)<tr><td class="px-5 py-4 font-extrabold">{{ $payslip->staff_id }}</td><td class="px-5 py-4"><p class="font-bold">{{ $payslip->employee_name }}</p><p class="text-xs text-gray-400">{{ $payslip->position }}</p></td><td class="px-5 py-4 text-sm"><p>{{ $payslip->account_number ?: '—' }}</p><p class="text-xs text-gray-400">PAN: {{ $payslip->pan_number ?: '—' }}</p></td><td class="px-5 py-4 text-right">{{ number_format($payslip->salary_before_tax,2) }}</td><td class="px-5 py-4 text-right">{{ number_format($payslip->tax_amount,2) }}</td><td class="px-5 py-4 text-right font-black">Rs. {{ number_format($payslip->net_amount,2) }}</td><td class="px-5 py-4 text-right"><a href="{{ route('admin.billing.payroll.show', $payslip) }}" class="rounded-lg border px-3 py-2 text-xs font-extrabold text-gray-700">View / Print</a></td></tr>@endforeach
    </tbody></table></div></div>
</div>
@endsection
