@extends('billing.layouts.app')
@section('title', 'Verify Payroll')
@section('content')
<div class="mx-auto max-w-[95rem] space-y-5">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-xs font-bold uppercase tracking-widest text-gray-400">Verify before upload</p><h1 class="text-2xl font-extrabold">{{ $monthName }} {{ $year }} BS</h1><p class="text-sm text-gray-500">{{ $filename }} · {{ count($rows) }} employee rows</p></div><a href="{{ route('admin.billing.payroll.upload') }}" class="rounded-xl border px-4 py-2.5 text-sm font-extrabold text-gray-700">Choose another file</a></div>
    @if($batch)<div class="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm font-bold text-amber-900">This month already exists (revision {{ $batch->revision }}). Confirming will replace all {{ $batch->row_count }} existing payslips and create revision {{ $batch->revision + 1 }}.</div>@endif
    @if($errors)<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><p class="font-extrabold">Fix these errors and upload again:</p><ul class="mt-2 list-disc space-y-1 pl-5">@foreach($errors as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="overflow-hidden rounded-2xl border bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-[1250px] w-full text-left text-xs"><thead class="bg-gray-50 uppercase tracking-wide text-gray-500"><tr><th class="p-3">Row</th><th class="p-3">Staff ID</th><th class="p-3">Name / Position</th><th class="p-3 text-right">Current</th><th class="p-3 text-right">Previous + Extra</th><th class="p-3 text-right">Allowance</th><th class="p-3 text-right">Abs.</th><th class="p-3 text-right">PF</th><th class="p-3 text-right">Advance</th><th class="p-3 text-right">Before Tax</th><th class="p-3 text-right">Tax</th><th class="p-3 text-right">Net</th><th class="p-3">Check</th></tr></thead><tbody class="divide-y">
        @foreach($rows as $row)<tr class="{{ !$row['user_id'] ? 'bg-red-50' : ($row['warnings'] ? 'bg-amber-50' : '') }}"><td class="p-3 text-gray-400">{{ $row['excel_row'] }}</td><td class="p-3 font-extrabold">{{ $row['staff_id'] }}</td><td class="p-3"><b>{{ $row['employee_name'] }}</b><br><span class="text-gray-400">{{ $row['position'] ?? '' }}</span></td><td class="p-3 text-right">{{ number_format($row['current_salary'],2) }}</td><td class="p-3 text-right">{{ number_format($row['previous_dues_extra'],2) }}</td><td class="p-3 text-right">{{ number_format($row['meeting_extra_allowance'],2) }}</td><td class="p-3 text-right">{{ number_format($row['absence_amount'],2) }}</td><td class="p-3 text-right">{{ number_format($row['provident_fund'],2) }}</td><td class="p-3 text-right">{{ number_format($row['advance'],2) }}</td><td class="p-3 text-right">{{ number_format($row['salary_before_tax'],2) }}</td><td class="p-3 text-right">{{ number_format($row['tax_amount'],2) }}</td><td class="p-3 text-right font-black">{{ number_format($row['net_amount'],2) }}</td><td class="p-3">@if(!$row['user_id'])<span class="font-bold text-red-700">No HR match</span>@elseif($row['warnings'])<span class="font-bold text-amber-700">{{ implode(' ', $row['warnings']) }}</span>@else<span class="font-bold text-green-700">Matched to {{ $row['matched_name'] }}</span>@endif</td></tr>@endforeach
    </tbody></table></div></div>
    <div class="flex justify-end"><form method="POST" action="{{ route('admin.billing.payroll.commit') }}">@csrf<input type="hidden" name="token" value="{{ $token }}"><button @disabled($errors) class="rounded-xl px-6 py-3 text-sm font-extrabold text-white {{ $errors ? 'cursor-not-allowed bg-gray-400' : ($batch ? 'bg-amber-600' : 'bg-[#1a5632]') }}">{{ $batch ? 'Confirm Re-upload & Replace Month' : 'Confirm Payroll Upload' }}</button></form></div>
</div>
@endsection
