@extends('examinations.layouts.app')
@section('title','Examination Dashboard')
@section('content')
@php $input='w-full rounded-lg border-gray-200 px-3 py-2 text-sm font-semibold focus:border-[#1a5632] focus:ring-[#1a5632]';$label='mb-1 block text-[10px] font-black uppercase tracking-wider text-gray-500'; @endphp
<div class="space-y-4" x-data="examCreator(@js($organizations))">
    <section class="flex flex-col gap-3 rounded-2xl bg-gradient-to-r from-[#0b2415] to-[#1a5632] p-5 text-white shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><p class="text-[10px] font-black uppercase tracking-widest text-amber-300">Assessment control</p><h1 class="mt-1 text-2xl font-black">Examinations</h1><p class="mt-1 text-xs font-semibold text-white/65">Plan exams, enter marks and evaluate performance from one workspace.</p></div>@if($canManage)<button @click="createOpen=!createOpen" class="rounded-xl bg-white px-4 py-2.5 text-xs font-black text-[#1a5632]" x-text="createOpen?'Close setup':'+ Create exam'"></button>@endif</section>
    @if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-3 text-xs font-bold text-red-700">@foreach($errors->all() as $error)<p>• {{$error}}</p>@endforeach</div>@endif

    @if($canManage)<section x-show="createOpen" x-cloak x-transition class="rounded-2xl border border-emerald-200 bg-white shadow-sm"><form method="POST" action="{{route('admin.examinations.store')}}" class="p-4">@csrf
        <div class="mb-3"><h2 class="text-sm font-black">Create an exam</h2><p class="text-[10px] font-semibold text-gray-400">Select the class and all participating sections. Subject marks are configured next.</p></div>
        <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><div><label class="{{$label}}">Academic year</label><select name="academic_year_id" required class="{{$input}}">@foreach($academicYears as $year)<option value="{{$year->id}}">{{$year->name}}{{$year->is_active?' · Active':''}}</option>@endforeach</select></div><div><label class="{{$label}}">Organization</label><select name="organization_id" x-model="orgId" @change="departmentId='';sections=[]" required class="{{$input}}"><option value="">Choose</option>@foreach($organizations as $org)<option value="{{$org->id}}">{{$org->name}}</option>@endforeach</select></div><div><label class="{{$label}}">Class / Faculty</label><select name="department_id" x-model="departmentId" @change="sections=[]" required class="{{$input}}"><option value="">Choose</option><template x-for="dept in departments" :key="dept.id"><option :value="String(dept.id)" x-text="dept.name"></option></template></select></div><div><label class="{{$label}}">Exam name</label><input name="name" value="{{old('name')}}" required placeholder="First Terminal 2083" class="{{$input}}"></div><div><label class="{{$label}}">Category</label><input name="category" list="exam-categories" value="{{old('category','Terminal')}}" required class="{{$input}}"><datalist id="exam-categories"><option>Unit Test</option><option>First Terminal</option><option>Second Terminal</option><option>Pre-board</option><option>Final</option><option>Practical</option></datalist></div><template x-if="department?.academic_system==='semester'"><div><label class="{{$label}}">Semester</label><select name="semester" class="{{$input}}"><option value="">All</option>@for($i=1;$i<=8;$i++)<option value="{{$i}}">Semester {{$i}}</option>@endfor</select></div></template><template x-if="department?.academic_system==='year'"><div><label class="{{$label}}">Study year</label><select name="year_level" class="{{$input}}"><option value="">All</option>@for($i=1;$i<=6;$i++)<option value="{{$i}}">Year {{$i}}</option>@endfor</select></div></template><div><label class="{{$label}}">Starts</label><input type="date" name="starts_on" value="{{old('starts_on')}}" class="{{$input}}"></div><div><label class="{{$label}}">Ends</label><input type="date" name="ends_on" value="{{old('ends_on')}}" class="{{$input}}"></div></div>
        <div class="mt-3 grid gap-3 sm:grid-cols-3"><div><label class="{{$label}}">Daily start time</label><input type="time" name="starts_at" value="{{old('starts_at')}}" class="{{$input}}"></div><div><label class="{{$label}}">Theory duration</label><div class="relative"><input type="number" name="theory_duration_minutes" min="1" max="600" value="{{old('theory_duration_minutes',180)}}" class="{{$input}}"><span class="pointer-events-none absolute right-3 top-2.5 text-[9px] font-bold text-gray-400">MIN</span></div></div><div><label class="{{$label}}">Practical duration</label><div class="relative"><input type="number" name="practical_duration_minutes" min="1" max="600" value="{{old('practical_duration_minutes',120)}}" class="{{$input}}"><span class="pointer-events-none absolute right-3 top-2.5 text-[9px] font-bold text-gray-400">MIN</span></div></div></div>
        <div class="mt-3"><p class="{{$label}}">Participating sections</p><div class="flex flex-wrap gap-2"><template x-for="section in availableSections" :key="section.id"><label :class="sections.includes(String(section.id))?'border-emerald-600 bg-emerald-600 text-white':'border-gray-200 bg-gray-50 text-gray-600'" class="flex cursor-pointer items-center gap-2 rounded-lg border px-3 py-2 text-xs font-black transition"><input class="sr-only" type="checkbox" name="section_ids[]" :value="section.id" x-model="sections"><span :class="sections.includes(String(section.id))?'bg-white text-emerald-700':'border border-gray-300 text-transparent'" class="flex h-4 w-4 items-center justify-center rounded"><span>✓</span></span><span x-text="section.name"></span><small x-show="section.group_name" x-text="section.group_name" class="opacity-70"></small></label></template><span x-show="departmentId && !availableSections.length" class="text-xs font-bold text-amber-600">Create sections first.</span></div></div>
        <div class="mt-4 flex justify-end"><button :disabled="!departmentId||!sections.length" class="rounded-lg bg-[#1a5632] px-5 py-2.5 text-xs font-black text-white disabled:opacity-40">Create and configure subjects</button></div>
    </form></section>@endif

    <div class="grid gap-4 xl:grid-cols-[1.25fr_.75fr]">
        <section class="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm"><header class="flex flex-col gap-2 border-b px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-sm font-black">Exam records</h2><p class="text-[10px] font-semibold text-gray-400">Draft, ongoing and conducted exams.</p></div><div class="flex flex-wrap items-center gap-1">@foreach([''=>'All','draft'=>'Draft','ongoing'=>'Ongoing','conducted'=>'Conducted'] as $status=>$text)<a href="{{route('admin.examinations.index',array_filter(['status'=>$status,'year'=>request('year'),'org'=>request('org')]))}}" class="rounded-lg px-2.5 py-1.5 text-[9px] font-black {{request('status','')===$status?'bg-[#1a5632] text-white':'bg-gray-100 text-gray-600 hover:bg-gray-200'}}">{{$text}}</a>@endforeach<span class="ml-1 rounded-full bg-gray-100 px-2.5 py-1 text-[10px] font-black text-gray-600">{{$examinations->count()}}</span></div></header><div class="divide-y">@forelse($examinations as $exam)<a href="{{route('admin.examinations.show',$exam)}}" class="flex items-center justify-between gap-3 px-4 py-3 hover:bg-gray-50"><div class="min-w-0"><div class="flex flex-wrap items-center gap-1.5"><p class="truncate text-sm font-black">{{$exam->name}}</p><span class="rounded-md px-2 py-0.5 text-[9px] font-black {{in_array($exam->status,['completed','published'])?'bg-emerald-50 text-emerald-700':($exam->status==='ongoing'?'bg-blue-50 text-blue-700':'bg-gray-100 text-gray-600')}}">{{strtoupper($exam->status)}}</span></div><p class="mt-1 text-[10px] font-semibold text-gray-400">{{$exam->academicYear->name}} · {{$exam->organization->name}} · {{$exam->department->name}} · {{$exam->sections->pluck('name')->implode(', ')}}</p></div><div class="flex shrink-0 gap-1.5 text-[9px] font-black"><span class="rounded bg-purple-50 px-2 py-1 text-purple-700">{{$exam->subjects_count}} subjects</span><span class="rounded bg-blue-50 px-2 py-1 text-blue-700">{{$exam->marks_count}} marks</span></div></a>@empty<div class="py-12 text-center text-sm font-bold text-gray-400">No {{request('status')?:''}} exams found.</div>@endforelse</div></section>
        <section class="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm"><div class="flex items-center justify-between"><div><p class="text-[10px] font-black uppercase tracking-wider text-emerald-600">Latest evaluation</p><h2 class="text-sm font-black">{{$selectedExam?->name??'No exam selected'}}</h2></div>@if($selectedExam)<a href="{{route('admin.examinations.show',$selectedExam)}}" class="text-[10px] font-black text-[#1a5632]">Open →</a>@endif</div>@if($snapshot)<div class="mt-4 grid grid-cols-2 gap-2"><div class="rounded-xl bg-emerald-50 p-3"><p class="text-2xl font-black text-emerald-700">{{$snapshot['pass_rate']}}%</p><p class="text-[10px] font-bold text-emerald-600">Pass percentage</p></div><div class="rounded-xl bg-red-50 p-3"><p class="text-2xl font-black text-red-700">{{$snapshot['fail_rate']}}%</p><p class="text-[10px] font-bold text-red-600">Mass fail percentage</p></div><div class="rounded-xl bg-blue-50 p-3"><p class="text-2xl font-black text-blue-700">{{$snapshot['average']}}%</p><p class="text-[10px] font-bold text-blue-600">Overall average</p></div><div class="rounded-xl bg-amber-50 p-3"><p class="truncate text-sm font-black text-amber-800">{{$snapshot['topper']['student']?->full_name??'—'}}</p><p class="text-[10px] font-bold text-amber-600">Topper · {{$snapshot['topper']['percentage']??0}}%</p></div></div>@else<p class="mt-8 text-center text-xs font-semibold text-gray-400">Create an exam to begin evaluation.</p>@endif</section>
    </div>
</div>
@endsection
@push('scripts')<script>function examCreator(orgs){return{createOpen:@js($errors->any()),orgId:@js((string)old('organization_id','')),departmentId:@js((string)old('department_id','')),sections:@js(collect(old('section_ids',[]))->map(fn($id)=>(string)$id)->values()),orgs,get organization(){return this.orgs.find(o=>String(o.id)===String(this.orgId))},get departments(){return this.organization?.departments||[]},get department(){return this.departments.find(d=>String(d.id)===String(this.departmentId))},get availableSections(){return this.department?.sections||[]}}}</script>@endpush
