@extends('examinations.layouts.app')
@section('title','Examinations')
@section('content')
@php $input='w-full rounded-xl border-gray-200 px-3 py-2.5 text-sm font-semibold focus:border-[#1a5632] focus:ring-[#1a5632]';$label='mb-1 block text-[10px] font-black uppercase tracking-wider text-gray-500'; @endphp
<div class="space-y-4" x-data="examCreator(@js($organizations))">
    <section class="flex flex-col gap-3 rounded-2xl bg-gradient-to-r from-[#0b2415] to-[#1a5632] p-5 text-white shadow-sm sm:flex-row sm:items-center sm:justify-between">
        <div><p class="text-[10px] font-black uppercase tracking-[.2em] text-amber-300">Assessment control</p><h1 class="mt-1 text-2xl font-black">Examinations</h1><p class="mt-1 text-xs font-semibold text-white/65">Choose who takes the exam, configure each unique subject once, then collect marks.</p></div>
        @if($canManage)<button @click="createOpen=!createOpen" class="rounded-xl bg-white px-4 py-2.5 text-xs font-black text-[#1a5632]" x-text="createOpen?'Close':'+ Create exam'"></button>@endif
    </section>
    @if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-3 text-xs font-bold text-red-700">@foreach($errors->all() as $error)<p>• {{$error}}</p>@endforeach</div>@endif

    @if($canManage)
    <section x-show="createOpen" x-cloak x-transition class="overflow-hidden rounded-2xl border border-emerald-200 bg-white shadow-sm">
        <form method="POST" action="{{route('admin.examinations.store')}}" class="p-4 sm:p-5">@csrf
            <div class="mb-4 flex items-start justify-between"><div><p class="text-[10px] font-black uppercase tracking-wider text-emerald-700">New examination</p><h2 class="text-lg font-black">Who is taking this exam?</h2><p class="text-xs font-semibold text-gray-400">All active sections inside the chosen scope are included automatically.</p></div><span class="rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-black text-emerald-700" x-text="sectionCount+' sections'"></span></div>
            <div class="grid gap-3 md:grid-cols-3"><div><label class="{{$label}}">Academic year</label><select name="academic_year_id" required class="{{$input}}">@foreach($academicYears as $year)<option value="{{$year->id}}" @selected(old('academic_year_id')==$year->id)>{{$year->name}}{{$year->is_active?' · Active':''}}</option>@endforeach</select></div><div><label class="{{$label}}">Organization</label><select name="organization_id" x-model="orgId" @change="departmentIds=[]" required class="{{$input}}"><option value="">Select organization</option>@foreach($organizations as $org)<option value="{{$org->id}}">{{$org->name}}</option>@endforeach</select></div><div><label class="{{$label}}">Exam name</label><input name="name" value="{{old('name')}}" required placeholder="First Terminal 2083" class="{{$input}}"></div></div>

            <div x-show="organization" class="mt-4"><p class="{{$label}}">Exam scope</p><div class="grid gap-2 sm:grid-cols-2">
                <label :class="scopeType==='organization'?'border-emerald-600 bg-emerald-50 ring-1 ring-emerald-600':'border-gray-200 bg-white'" class="cursor-pointer rounded-xl border p-3 transition"><input type="radio" name="scope_type" value="organization" x-model="scopeType" class="sr-only"><span class="flex items-center gap-3"><span :class="scopeType==='organization'?'bg-emerald-600 text-white':'bg-gray-100 text-gray-400'" class="grid h-8 w-8 place-items-center rounded-lg font-black">✓</span><span><b class="block text-sm">Whole organization</b><small class="text-[10px] font-semibold text-gray-500">Every faculty/class and active section</small></span></span></label>
                <label :class="scopeType==='departments'?'border-blue-600 bg-blue-50 ring-1 ring-blue-600':'border-gray-200 bg-white'" class="cursor-pointer rounded-xl border p-3 transition"><input type="radio" name="scope_type" value="departments" x-model="scopeType" class="sr-only"><span class="flex items-center gap-3"><span :class="scopeType==='departments'?'bg-blue-600 text-white':'bg-gray-100 text-gray-400'" class="grid h-8 w-8 place-items-center rounded-lg font-black">✓</span><span><b class="block text-sm">Choose faculties/classes</b><small class="text-[10px] font-semibold text-gray-500">Only selected academic units</small></span></span></label>
            </div></div>
            <div x-show="organization && scopeType==='departments'" x-cloak class="mt-3 rounded-xl border border-blue-100 bg-blue-50/40 p-3"><p class="{{$label}}">Select one or more faculties/classes</p><div class="flex flex-wrap gap-2"><template x-for="dept in departments" :key="dept.id"><label :class="departmentIds.includes(String(dept.id))?'border-blue-600 bg-blue-600 text-white':'border-gray-200 bg-white text-gray-600'" class="cursor-pointer rounded-lg border px-3 py-2 text-xs font-black transition"><input type="checkbox" name="department_ids[]" :value="dept.id" x-model="departmentIds" class="sr-only"><span x-text="(departmentIds.includes(String(dept.id))?'✓ ':'')+dept.name"></span><small class="ml-1 opacity-70" x-text="dept.sections.length+' sec'"></small></label></template></div></div>

            <div class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><label class="{{$label}}">Category</label><select name="category" class="{{$input}}">@foreach(['Unit Test','First Terminal','Second Terminal','Pre-board','Final','Practical'] as $category)<option @selected(old('category','First Terminal')===$category)>{{$category}}</option>@endforeach</select></div><template x-if="selectedDepartment && departmentIds.length===1 && selectedDepartment.academic_system==='semester'"><div><label class="{{$label}}">Semester</label><select name="semester" class="{{$input}}"><option value="">All semesters</option>@for($i=1;$i<=8;$i++)<option value="{{$i}}">Semester {{$i}}</option>@endfor</select></div></template><template x-if="selectedDepartment && departmentIds.length===1 && selectedDepartment.academic_system==='year'"><div><label class="{{$label}}">Study year</label><select name="year_level" class="{{$input}}"><option value="">All years</option>@for($i=1;$i<=6;$i++)<option value="{{$i}}">Year {{$i}}</option>@endfor</select></div></template><div><label class="{{$label}}">Starts on</label><input type="date" name="starts_on" value="{{old('starts_on')}}" class="{{$input}}"></div><div><label class="{{$label}}">Ends on</label><input type="date" name="ends_on" value="{{old('ends_on')}}" class="{{$input}}"></div></div>
            <div class="mt-3 grid gap-3 sm:grid-cols-3"><div><label class="{{$label}}">Daily start</label><input type="time" name="starts_at" value="{{old('starts_at')}}" class="{{$input}}"></div><div><label class="{{$label}}">Theory duration (minutes)</label><input type="number" name="theory_duration_minutes" min="1" max="600" value="{{old('theory_duration_minutes',180)}}" class="{{$input}}"></div><div><label class="{{$label}}">Practical duration (minutes)</label><input type="number" name="practical_duration_minutes" min="1" max="600" value="{{old('practical_duration_minutes',120)}}" class="{{$input}}"></div></div>
            <div class="mt-4 flex items-center justify-between gap-3 border-t pt-4"><p class="text-[10px] font-semibold text-gray-400" x-text="scopeSummary"></p><button :disabled="!canCreate" class="shrink-0 rounded-xl bg-[#1a5632] px-5 py-3 text-xs font-black text-white disabled:cursor-not-allowed disabled:opacity-40">Create & configure →</button></div>
        </form>
    </section>
    @endif

    @if($selectedExam) @include('examinations.partials.exam-workspace', ['examination'=>$selectedExam]) @endif

    <section class="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm">
        <header class="flex flex-col gap-2 border-b px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-sm font-black">Exam records</h2><p class="text-[10px] font-semibold text-gray-400">Open a record here; configuration stays on this page.</p></div><div class="flex flex-wrap items-center gap-1">@foreach([''=>'All','draft'=>'Draft','ongoing'=>'Ongoing','conducted'=>'Conducted'] as $status=>$text)<a href="{{route('admin.examinations.index',array_filter(['status'=>$status,'year'=>request('year'),'org'=>request('org')]))}}" class="rounded-lg px-2.5 py-1.5 text-[9px] font-black {{request('status','')===$status?'bg-[#1a5632] text-white':'bg-gray-100 text-gray-600'}}">{{$text}}</a>@endforeach<span class="ml-1 rounded-full bg-gray-100 px-2.5 py-1 text-[10px] font-black text-gray-600">{{$examinations->count()}}</span></div></header>
        <div class="grid gap-px bg-gray-100 sm:grid-cols-2 xl:grid-cols-3">@forelse($examinations as $exam)<a href="{{route('admin.examinations.index',['exam'=>$exam->id])}}" class="min-w-0 bg-white p-4 transition hover:bg-emerald-50/40"><div class="flex items-start justify-between gap-2"><div class="min-w-0"><p class="truncate text-sm font-black">{{$exam->name}}</p><p class="mt-1 truncate text-[10px] font-bold text-gray-400">{{$exam->organization->name}} · {{$exam->academicYear->name}}</p></div><span class="rounded-md px-2 py-1 text-[8px] font-black {{in_array($exam->status,['completed','published'])?'bg-emerald-50 text-emerald-700':($exam->status==='ongoing'?'bg-blue-50 text-blue-700':'bg-gray-100 text-gray-600')}}">{{strtoupper($exam->status)}}</span></div><p class="mt-3 line-clamp-2 text-[10px] font-semibold text-gray-500">{{$exam->scope_type==='organization'?'Whole organization':$exam->departments->pluck('name')->implode(', ')}}</p><div class="mt-3 flex flex-wrap gap-1.5"><span class="rounded bg-purple-50 px-2 py-1 text-[9px] font-black text-purple-700">{{$exam->subjects_count}} subjects</span><span class="rounded bg-blue-50 px-2 py-1 text-[9px] font-black text-blue-700">{{$exam->marks_count}} entries</span><span class="rounded bg-gray-50 px-2 py-1 text-[9px] font-black text-gray-600">{{$exam->sections->count()}} sections</span></div></a>@empty<div class="col-span-full py-12 text-center text-sm font-bold text-gray-400">No exams found.</div>@endforelse</div>
    </section>
</div>
@endsection
@push('scripts')<script>function examCreator(orgs){return{createOpen:@js($errors->any()),orgId:@js((string)old('organization_id','')),scopeType:@js(old('scope_type','organization')),departmentIds:@js(collect(old('department_ids',[]))->map(fn($id)=>(string)$id)->values()),orgs,get organization(){return this.orgs.find(o=>String(o.id)===String(this.orgId))},get departments(){return this.organization?.departments||[]},get selectedDepartment(){return this.departments.find(d=>String(d.id)===String(this.departmentIds[0]))},get selectedDepartments(){return this.departments.filter(d=>this.departmentIds.includes(String(d.id)))},get sectionCount(){return this.scopeType==='organization'?this.departments.reduce((n,d)=>n+d.sections.length,0):this.selectedDepartments.reduce((n,d)=>n+d.sections.length,0)},get canCreate(){return this.orgId&&this.sectionCount>0&&(this.scopeType==='organization'||this.departmentIds.length>0)},get scopeSummary(){if(!this.organization)return 'Select an organization to continue.';return this.scopeType==='organization'?'Includes all '+this.departments.length+' faculties/classes and '+this.sectionCount+' sections.':'Includes '+this.departmentIds.length+' selected faculties/classes and '+this.sectionCount+' sections.'}}}</script>@endpush
