@extends('examinations.layouts.app')
@section('title','Marks Entry')
@section('content')
<div class="mx-auto max-w-6xl space-y-4">
    <section class="rounded-2xl bg-gradient-to-r from-[#0b2415] to-[#1a5632] p-4 text-white shadow-sm"><p class="text-[9px] font-black uppercase tracking-widest text-amber-300">Administrator workspace</p><h1 class="mt-1 text-xl font-black">Marks Entry</h1><p class="mt-1 text-xs font-semibold text-white/65">Choose an exam, faculty, section, and subject to enter marks.</p></section>
    <section class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
        <form method="GET" action="{{route('admin.examinations.marks.dashboard')}}" class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            <label><span class="mb-1 block text-[9px] font-black uppercase tracking-wider text-slate-500">Exam</span><select name="exam" onchange="this.form.submit()" class="w-full rounded-xl border-slate-200 text-sm font-bold"><option value="">Choose exam</option>@foreach($exams as $item)<option value="{{$item->id}}" @selected($exam?->id===$item->id)>{{$item->name}} · {{$item->academicYear->name}}</option>@endforeach</select></label>
            <label><span class="mb-1 block text-[9px] font-black uppercase tracking-wider text-slate-500">Faculty / class</span><select name="faculty" onchange="this.form.submit()" @disabled(!$exam) class="w-full rounded-xl border-slate-200 text-sm font-bold"><option value="">All faculties</option>@foreach($faculties as $faculty)<option value="{{$faculty->id}}" @selected($facultyId===$faculty->id)>{{$faculty->name}}</option>@endforeach</select></label>
            <label><span class="mb-1 block text-[9px] font-black uppercase tracking-wider text-slate-500">Section</span><select name="section" onchange="this.form.submit()" @disabled(!$exam) class="w-full rounded-xl border-slate-200 text-sm font-bold"><option value="">Choose section</option>@foreach($sections as $item)<option value="{{$item->id}}" @selected($section?->id===$item->id)>{{$item->name}}</option>@endforeach</select></label>
            <div class="flex items-end"><a href="{{route('admin.examinations.marks.dashboard')}}" class="w-full rounded-xl border border-slate-200 px-4 py-2.5 text-center text-xs font-black text-slate-600">Reset choices</a></div>
        </form>
    </section>
    @if($section)
    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header class="border-b border-slate-200 px-4 py-3"><p class="text-[9px] font-black uppercase tracking-widest text-emerald-700">{{$section->name}} section</p><h2 class="mt-0.5 text-base font-black">Subjects still needing marks</h2></header><div class="divide-y divide-slate-100">@forelse($subjects as $entry)<article class="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><h3 class="text-sm font-black text-slate-900">{{$entry->offering->subject->name}}</h3><p class="mt-0.5 text-[10px] font-bold text-slate-400">Theory FM {{$entry->theory_full_marks}} · PM {{$entry->theory_pass_marks}} @if((float)$entry->practical_full_marks>0) · Practical FM {{$entry->practical_full_marks}} · PM {{$entry->practical_pass_marks}} @endif</p></div><div class="flex flex-wrap gap-2">@if((float)$entry->theory_full_marks>0)<a href="{{route('admin.examinations.marks.edit',[$entry,'component'=>'theory','section'=>$section->id])}}" class="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-black text-white">Enter theory</a>@endif @if((float)$entry->practical_full_marks>0)<a href="{{route('admin.examinations.marks.edit',[$entry,'component'=>'practical','section'=>$section->id])}}" class="rounded-lg bg-purple-700 px-3 py-2 text-xs font-black text-white">Enter practical</a>@endif</div></article>@empty<div class="p-10 text-center text-sm font-semibold text-slate-400">No subjects found for these choices.</div>@endforelse</div></section>
    @else
    <section class="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><p class="text-sm font-black text-slate-700">Choose a section to see its subjects and start entering marks.</p></section>
    @endif
</div>
@endsection
