@extends('examinations.layouts.app')
@section('title',$examination->name)
@section('content')
@php $input='w-full rounded-lg border-gray-200 px-2.5 py-2 text-xs font-semibold focus:border-[#1a5632] focus:ring-[#1a5632]';$label='mb-1 block text-[9px] font-black uppercase tracking-wider text-gray-500'; @endphp
<div class="space-y-4">
    <section class="flex flex-col gap-3 rounded-2xl bg-gradient-to-r from-[#0b2415] to-[#1a5632] p-5 text-white shadow-sm lg:flex-row lg:items-center lg:justify-between"><div><div class="flex flex-wrap items-center gap-2"><span class="rounded-md bg-white/10 px-2 py-1 text-[9px] font-black uppercase">{{$examination->category}}</span><span class="rounded-md bg-amber-400/20 px-2 py-1 text-[9px] font-black uppercase text-amber-200">{{$examination->status}}</span></div><h1 class="mt-2 text-2xl font-black">{{$examination->name}}</h1><p class="mt-1 text-xs font-semibold text-white/65">{{$examination->academicYear->name}} · {{$examination->organization->name}} · {{$examination->department->name}} · {{$examination->sections->pluck('name')->implode(', ')}}</p></div><div class="flex gap-2"><a href="{{route('admin.examinations.index')}}" class="rounded-xl border border-white/20 bg-white/10 px-4 py-2.5 text-xs font-black">All exams</a>@if($canManage)<button type="button" onclick="document.getElementById('exam-details').showModal()" class="rounded-xl bg-white px-4 py-2.5 text-xs font-black text-[#1a5632]">Edit exam</button>@endif</div></section>
    @if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-3 text-xs font-bold text-red-700">@foreach($errors->all() as $error)<p>• {{$error}}</p>@endforeach</div>@endif

    @if($canManage)
    <dialog id="exam-details" class="m-auto w-[calc(100%_-_2rem)] max-w-2xl rounded-2xl p-0 shadow-2xl backdrop:bg-gray-950/60"><form method="POST" action="{{route('admin.examinations.update',$examination)}}">@csrf @method('PATCH')<header class="flex items-center justify-between border-b px-5 py-4"><div><p class="text-[10px] font-black uppercase text-[#1a5632]">Exam settings</p><h2 class="font-black">Edit {{$examination->name}}</h2></div><button type="button" onclick="this.closest('dialog').close()" class="h-8 w-8 rounded-full bg-gray-100 text-xl">×</button></header><div class="grid gap-3 p-5 sm:grid-cols-2"><div><label class="{{$label}}">Name</label><input name="name" value="{{$examination->name}}" required class="{{$input}}"></div><div><label class="{{$label}}">Category</label><input name="category" value="{{$examination->category}}" required class="{{$input}}"></div><div><label class="{{$label}}">Starts</label><input type="date" name="starts_on" value="{{$examination->starts_on?->format('Y-m-d')}}" class="{{$input}}"></div><div><label class="{{$label}}">Ends</label><input type="date" name="ends_on" value="{{$examination->ends_on?->format('Y-m-d')}}" class="{{$input}}"></div><div><label class="{{$label}}">Daily start time</label><input type="time" name="starts_at" value="{{substr((string)$examination->starts_at,0,5)}}" class="{{$input}}"></div><div class="grid grid-cols-2 gap-2"><div><label class="{{$label}}">Theory minutes</label><input type="number" name="theory_duration_minutes" min="1" max="600" value="{{$examination->theory_duration_minutes??180}}" class="{{$input}}"></div><div><label class="{{$label}}">Practical minutes</label><input type="number" name="practical_duration_minutes" min="1" max="600" value="{{$examination->practical_duration_minutes??120}}" class="{{$input}}"></div></div><div><label class="{{$label}}">Status</label><select name="status" class="{{$input}}">@foreach(['draft'=>'Draft — setup','ongoing'=>'Ongoing — marks open','completed'=>'Completed — marks locked','published'=>'Published — final'] as $value=>$text)<option value="{{$value}}" @selected($examination->status===$value)>{{$text}}</option>@endforeach</select></div><div><label class="{{$label}}">Sections</label><div class="flex flex-wrap gap-1.5">@foreach($examination->department->sections as $section)<label class="rounded-md border px-2 py-1.5 text-[10px] font-bold"><input type="checkbox" name="section_ids[]" value="{{$section->id}}" @checked($examination->sections->contains('id',$section->id)) class="mr-1 rounded text-[#1a5632]">{{$section->name}}</label>@endforeach</div></div><div class="sm:col-span-2"><label class="{{$label}}">Notes</label><textarea name="notes" rows="2" class="{{$input}}">{{$examination->notes}}</textarea></div></div><footer class="flex justify-end border-t px-5 py-4"><button class="rounded-lg bg-[#1a5632] px-5 py-2 text-xs font-black text-white">Save exam setup</button></footer></form></dialog>
    @endif

    <section class="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm">
        @include('examinations.partials.subject-table')
        {{-- Replaced by the compact table partial above.
        <header class="flex items-center justify-between border-b px-4 py-3"><div><h2 class="text-sm font-black">Exam schedule and marks scheme</h2><p class="text-[10px] font-semibold text-gray-400">Theory and practical use separate codes, teachers, schedules and mark-entry screens.</p></div><span class="rounded-full bg-purple-50 px-2.5 py-1 text-[10px] font-black text-purple-700">{{$examination->subjects->count()}} configured</span></header>
        @if($canManage && !$examination->is_locked)
            <form method="POST" action="{{route('admin.examinations.subjects.update',$examination)}}">@csrf @method('PUT')
                <div class="divide-y divide-gray-100">
                    @forelse($offerings as $offering)
                        @php $set=$configured->get($offering->id);$practical=$offering->subject->has_practical;$practicalCode=$offering->subject->practical_code?:$offering->subject->code; @endphp
                        <article x-data="{enabled:@js((bool)$set),open:@js((bool)$set)}" :class="enabled?'bg-white':'bg-gray-50/70'" class="px-4 py-3 transition">
                            <div class="flex items-center gap-3">
                                <label class="flex min-w-0 flex-1 cursor-pointer items-center gap-2"><input type="hidden" name="subjects[{{$offering->id}}][enabled]" value="0"><input type="checkbox" name="subjects[{{$offering->id}}][enabled]" value="1" x-model="enabled" @change="if(enabled)open=true" class="rounded text-[#1a5632]"><span class="min-w-0"><span class="block truncate text-xs font-black">{{$offering->subject->name}}</span><span class="text-[9px] font-bold text-gray-400">{{$offering->subject->code}}{{$practical?' / '.$practicalCode:''}} · {{$offering->is_elective?'Assigned elective':'Compulsory'}}{{$offering->group_name?' · '.$offering->group_name:''}}</span></span></label>
                                @if($set)<div class="flex gap-1.5"><a href="{{route('admin.examinations.marks.edit',[$set,'component'=>'theory'])}}" class="rounded-lg bg-emerald-600 px-3 py-2 text-[10px] font-black text-white">{{$offering->subject->code}} marks</a>@if((float)$set->practical_full_marks>0)<a href="{{route('admin.examinations.marks.edit',[$set,'component'=>'practical'])}}" class="rounded-lg bg-purple-600 px-3 py-2 text-[10px] font-black text-white">{{$practicalCode}} marks</a>@endif</div>@endif
                                <button type="button" @click="open=!open" class="rounded-lg border px-3 py-2 text-[10px] font-black" x-text="open?'Hide':'Configure'"></button>
                            </div>
                            <div x-show="open" x-cloak class="mt-3 grid gap-3 lg:grid-cols-2">
                                <section class="rounded-xl border border-emerald-100 bg-emerald-50/40 p-3"><div class="mb-2 flex items-center justify-between"><div><p class="text-[9px] font-black uppercase text-emerald-700">Theory examination</p><p class="text-xs font-black">{{$offering->subject->code}}</p></div><span class="rounded bg-white px-2 py-1 text-[9px] font-bold">Whole section</span></div><div class="grid grid-cols-2 gap-2 sm:grid-cols-6"><div class="col-span-2"><label class="{{$label}}">Theory teacher</label><select name="subjects[{{$offering->id}}][teacher_id]" :disabled="!enabled" class="{{$input}}"><option value="">Assign later</option>@foreach($teachers as $teacher)<option value="{{$teacher->id}}" @selected((int)$set?->teacher_id===$teacher->id)>{{$teacher->name}}</option>@endforeach</select></div><div><label class="{{$label}}">FM</label><input type="number" step="0.01" name="subjects[{{$offering->id}}][theory_full_marks]" value="{{$set?->theory_full_marks??($practical?75:100)}}" :disabled="!enabled" class="{{$input}}"></div><div><label class="{{$label}}">PM</label><input type="number" step="0.01" name="subjects[{{$offering->id}}][theory_pass_marks]" value="{{$set?->theory_pass_marks??($practical?30:40)}}" :disabled="!enabled" class="{{$input}}"></div><div class="col-span-2"><label class="{{$label}}">Date</label><input type="date" name="subjects[{{$offering->id}}][exam_date]" value="{{$set?->exam_date?->format('Y-m-d')}}" :disabled="!enabled" class="{{$input}}"></div><div><label class="{{$label}}">Start</label><input type="time" name="subjects[{{$offering->id}}][starts_at]" value="{{substr((string)$set?->starts_at,0,5)}}" :disabled="!enabled" class="{{$input}}"></div><div><label class="{{$label}}">Minutes</label><input type="number" name="subjects[{{$offering->id}}][duration_minutes]" value="{{$set?->duration_minutes??180}}" :disabled="!enabled" class="{{$input}}"></div></div></section>
                                @if($practical)<section class="rounded-xl border border-purple-100 bg-purple-50/40 p-3"><div class="mb-2 flex items-center justify-between"><div><p class="text-[9px] font-black uppercase text-purple-700">Practical examination</p><p class="text-xs font-black">{{$practicalCode}}</p></div><span class="rounded bg-white px-2 py-1 text-[9px] font-bold">Separate sitting</span></div><div class="grid grid-cols-2 gap-2 sm:grid-cols-6"><div class="col-span-2"><label class="{{$label}}">Practical teacher</label><select name="subjects[{{$offering->id}}][practical_teacher_id]" :disabled="!enabled" class="{{$input}}"><option value="">Assign later</option>@foreach($teachers as $teacher)<option value="{{$teacher->id}}" @selected((int)$set?->practical_teacher_id===$teacher->id)>{{$teacher->name}}</option>@endforeach</select></div><div><label class="{{$label}}">FM</label><input type="number" step="0.01" name="subjects[{{$offering->id}}][practical_full_marks]" value="{{$set?->practical_full_marks??25}}" :disabled="!enabled" class="{{$input}}"></div><div><label class="{{$label}}">PM</label><input type="number" step="0.01" name="subjects[{{$offering->id}}][practical_pass_marks]" value="{{$set?->practical_pass_marks??10}}" :disabled="!enabled" class="{{$input}}"></div><div class="col-span-2"><label class="{{$label}}">Date</label><input type="date" name="subjects[{{$offering->id}}][practical_exam_date]" value="{{$set?->practical_exam_date?->format('Y-m-d')}}" :disabled="!enabled" class="{{$input}}"></div><div><label class="{{$label}}">Start</label><input type="time" name="subjects[{{$offering->id}}][practical_starts_at]" value="{{substr((string)$set?->practical_starts_at,0,5)}}" :disabled="!enabled" class="{{$input}}"></div><div><label class="{{$label}}">Minutes</label><input type="number" name="subjects[{{$offering->id}}][practical_duration_minutes]" value="{{$set?->practical_duration_minutes??120}}" :disabled="!enabled" class="{{$input}}"></div></div></section>@endif
                            </div>
                        </article>
                    @empty<div class="p-8 text-center"><p class="text-sm font-black text-gray-500">No subjects available for these sections</p><p class="mt-1 text-xs font-semibold text-gray-400">Assign elective students first; compulsory subjects appear automatically.</p></div>@endforelse
                </div>
                <div class="sticky bottom-0 flex items-center justify-between border-t bg-white/95 px-4 py-3 backdrop-blur"><p class="text-[10px] font-semibold text-gray-400">Open any subject to edit its schedule later.</p><button class="rounded-lg bg-[#1a5632] px-5 py-2.5 text-xs font-black text-white">Save exam schedule</button></div>
            </form>
        @else
            <div class="divide-y">@forelse($examination->subjects as $subject)@php $canTheory=auth()->user()->canAccess(['examinations.manage','examinations.marks.verify'])||(int)$subject->teacher_id===auth()->id();$canPractical=auth()->user()->canAccess(['examinations.manage','examinations.marks.verify'])||(int)$subject->practical_teacher_id===auth()->id(); @endphp<div class="flex items-center justify-between gap-3 px-4 py-3"><div><p class="text-sm font-black">{{$subject->offering->subject->name}}</p><p class="text-[10px] font-bold text-gray-400">Theory {{$subject->offering->subject->code}} · {{$subject->theory_full_marks}}/{{$subject->theory_pass_marks}} · {{$subject->teacher?->name??'Unassigned'}}@if((float)$subject->practical_full_marks>0)<br>Practical {{$subject->offering->subject->practical_code?:$subject->offering->subject->code}} · {{$subject->practical_full_marks}}/{{$subject->practical_pass_marks}} · {{$subject->practicalTeacher?->name??'Unassigned'}}@endif</p></div><div class="flex gap-1.5">@if($canTheory)<a href="{{route('admin.examinations.marks.edit',[$subject,'component'=>'theory'])}}" class="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-black text-white">Theory marks</a>@endif @if((float)$subject->practical_full_marks>0&&$canPractical)<a href="{{route('admin.examinations.marks.edit',[$subject,'component'=>'practical'])}}" class="rounded-lg bg-purple-600 px-3 py-2 text-xs font-black text-white">Practical marks</a>@endif</div></div>@empty<p class="p-8 text-center text-sm font-bold text-gray-400">No subjects configured.</p>@endforelse</div>
        @endif --}}
    </section>

    @if($examination->subjects->isNotEmpty())<section class="space-y-3"><div class="flex items-end justify-between"><div><p class="text-[10px] font-black uppercase tracking-wider text-emerald-600">Overall evaluation</p><h2 class="text-lg font-black">Result statistics</h2></div><p class="text-[10px] font-semibold text-gray-400">Calculated from entered marks</p></div><div class="grid grid-cols-2 gap-2 md:grid-cols-4 xl:grid-cols-8">@foreach([['Students',$analytics['students'],'gray'],['Pass %',$analytics['pass_rate'].'%','emerald'],['Fail %',$analytics['fail_rate'].'%','red'],['Average',$analytics['average'].'%','blue'],['Passed',$analytics['passed'],'emerald'],['Failed',$analytics['failed'],'red'],['Absent',$analytics['absent'],'amber'],['Incomplete',$analytics['incomplete'],'gray']] as [$text,$number,$color])<div class="rounded-xl border border-{{$color}}-100 bg-{{$color}}-50 p-3"><p class="text-xl font-black text-{{$color}}-700">{{$number}}</p><p class="text-[9px] font-black uppercase text-{{$color}}-600">{{$text}}</p></div>@endforeach</div>
        <div class="grid gap-3 lg:grid-cols-3"><div class="rounded-xl border border-amber-200 bg-amber-50 p-4"><p class="text-[9px] font-black uppercase text-amber-700">Overall topper</p><p class="mt-1 text-lg font-black text-amber-950">{{$analytics['topper']['student']?->full_name??'No complete result'}}</p><p class="text-xs font-bold text-amber-700">{{$analytics['topper']['percentage']??0}}% · {{ucfirst($analytics['topper']['student']?->gender??'Not specified')}}</p></div>@foreach(['male'=>'Male performance','female'=>'Female performance'] as $key=>$text)<div class="rounded-xl border border-blue-100 bg-white p-4"><p class="text-[9px] font-black uppercase text-blue-600">{{$text}}</p><div class="mt-2 flex gap-4"><span><b class="block text-lg">{{$analytics['gender'][$key]['average']}}%</b><small class="text-gray-400">Average</small></span><span><b class="block text-lg">{{$analytics['gender'][$key]['pass_rate']}}%</b><small class="text-gray-400">Pass rate</small></span><span><b class="block text-lg">{{$analytics['gender'][$key]['students']}}</b><small class="text-gray-400">Students</small></span></div><p class="mt-2 truncate text-[10px] font-bold text-blue-700">Top: {{$analytics['gender'][$key]['topper']['student']?->full_name??'—'}} · {{$analytics['gender'][$key]['topper']['percentage']??0}}%</p></div>@endforeach</div>
        <div class="overflow-hidden rounded-xl border bg-white"><header class="flex items-center justify-between border-b px-4 py-3"><h3 class="text-sm font-black">Subject evaluation</h3>@if($analytics['max_failed_subject'])<span class="rounded-full bg-red-50 px-2.5 py-1 text-[9px] font-black text-red-700">Highest failures: {{$analytics['max_failed_subject']['subject']->offering->subject->name}} ({{$analytics['max_failed_subject']['failed']}})</span>@endif</header><div class="overflow-x-auto"><table class="min-w-full divide-y text-xs"><thead class="bg-gray-50 text-[9px] font-black uppercase text-gray-500"><tr><th class="px-4 py-2 text-left">Subject</th><th class="px-3 py-2">Entered</th><th class="px-3 py-2">Passed</th><th class="px-3 py-2">Failed</th><th class="px-3 py-2">Pass %</th><th class="px-3 py-2">Average</th><th class="px-3 py-2">Highest</th><th class="px-4 py-2 text-right">Marks</th></tr></thead><tbody class="divide-y">@foreach($analytics['subject_stats'] as $row)<tr><td class="px-4 py-2.5 font-black">{{$row['subject']->offering->subject->name}} <span class="text-gray-400">{{$row['subject']->offering->subject->code}}</span></td><td class="px-3 py-2 text-center">{{$row['entered']}}</td><td class="px-3 py-2 text-center text-emerald-700">{{$row['passed']}}</td><td class="px-3 py-2 text-center text-red-700">{{$row['failed']}}</td><td class="px-3 py-2 text-center">{{$row['pass_rate']}}%</td><td class="px-3 py-2 text-center">{{$row['average']}}%</td><td class="px-3 py-2 text-center">{{$row['highest']}}%</td><td class="px-4 py-2 text-right"><a href="{{route('admin.examinations.marks.edit',$row['subject'])}}" class="font-black text-purple-700">Open →</a></td></tr>@endforeach</tbody></table></div></div>
        <div class="overflow-hidden rounded-xl border bg-white"><header class="flex items-center justify-between border-b px-4 py-3"><div><h3 class="text-sm font-black">Student result records</h3><p class="text-[9px] font-semibold text-gray-400">Every enrolled student, including incomplete results.</p></div><span class="rounded-full bg-gray-100 px-2 py-1 text-[9px] font-black text-gray-600">{{$analytics['student_results']->count()}} students</span></header><div class="max-h-[28rem] overflow-auto"><table class="min-w-full divide-y text-xs"><thead class="sticky top-0 bg-gray-50 text-[9px] font-black uppercase text-gray-500"><tr><th class="px-4 py-2 text-left">Rank / Student</th><th class="px-3 py-2">Gender</th><th class="px-3 py-2">Marks</th><th class="px-3 py-2">Percentage</th><th class="px-3 py-2">Failed subjects</th><th class="px-4 py-2 text-right">Result</th></tr></thead><tbody class="divide-y">@foreach($analytics['student_results'] as $row)<tr><td class="px-4 py-2.5"><span class="mr-2 text-[10px] font-black text-gray-400">#{{$loop->iteration}}</span><span class="font-black">{{$row['student']?->full_name}}</span><span class="ml-1 text-gray-400">{{$row['student']?->roll_number}}</span></td><td class="px-3 py-2 text-center">{{ucfirst($row['student']?->gender??'—')}}</td><td class="px-3 py-2 text-center font-bold">{{$row['obtained']}} / {{$row['full']}}</td><td class="px-3 py-2 text-center font-black">{{$row['percentage']}}%</td><td class="px-3 py-2 text-center text-red-600">{{$row['failed_subjects']}}</td><td class="px-4 py-2 text-right"><span class="rounded-md px-2 py-1 text-[9px] font-black {{$row['incomplete']?'bg-gray-100 text-gray-600':($row['passed']?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700')}}">{{$row['incomplete']?'INCOMPLETE':($row['passed']?'PASS':'FAIL')}}</span></td></tr>@endforeach</tbody></table></div></div>
    </section>@endif
</div>
@endsection
