@extends('teaching_learning.layouts.app')
@section('title','Routine Builder')
@section('content')
@php $input='w-full rounded-lg border-gray-200 px-3 py-2 text-xs font-semibold focus:border-[#1a5632] focus:ring-[#1a5632]';$label='mb-1 block text-[9px] font-black uppercase tracking-wider text-gray-500'; @endphp
<div class="space-y-4" x-data="planCreator(@js($organizations),@js($shifts))">
    <section class="flex flex-col gap-3 rounded-2xl bg-gradient-to-r from-[#0b2415] to-[#1a5632] p-5 text-white sm:flex-row sm:items-center sm:justify-between"><div><p class="text-[10px] font-black uppercase tracking-widest text-amber-300">Collision-safe scheduling</p><h1 class="mt-1 text-2xl font-black">Routine Builder</h1><p class="mt-1 text-xs font-semibold text-white/65">Build compact section routines with teacher initials, rooms and parallel 50/50 practical groups.</p></div><div class="flex gap-2"><a href="{{route('admin.teaching-learning.routine-configuration.index')}}" class="rounded-xl border border-white/20 bg-white/10 px-4 py-2.5 text-xs font-black">Time slots</a><button @click="createOpen=!createOpen" class="rounded-xl bg-white px-4 py-2.5 text-xs font-black text-[#1a5632]" x-text="createOpen?'Close':'+ New routine'"></button></div></section>
    @if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-3 text-xs font-bold text-red-700">@foreach($errors->all() as $error)<p>• {{$error}}</p>@endforeach</div>@endif

    <section x-show="createOpen" x-cloak x-transition class="rounded-2xl border border-emerald-200 bg-white p-4 shadow-sm">
        <div class="mb-3"><h2 class="text-sm font-black">Create a routine workspace</h2><p class="text-[10px] font-semibold text-gray-400">Choose the assigned time slot; its working days, periods and break are used automatically.</p></div>
        <form method="POST" action="{{route('admin.teaching-learning.routine-builder.plans.store')}}">@csrf
            <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">
                <div><label class="{{$label}}">Academic year</label><select name="academic_year_id" x-model="yearId" @change="syncShift()" required class="{{$input}}"><option value="">Choose</option>@foreach($academicYears as $year)<option value="{{$year->id}}">{{$year->name}}{{$year->is_active?' · Active':''}}</option>@endforeach</select></div>
                <div><label class="{{$label}}">Organization</label><select name="organization_id" x-model="orgId" @change="departmentId='';sectionIds=[];shiftId='';syncShift()" required class="{{$input}}"><option value="">Choose</option>@foreach($organizations as $org)<option value="{{$org->id}}">{{$org->name}}</option>@endforeach</select></div>
                <div><label class="{{$label}}">Faculty / Class</label><select name="department_id" x-model="departmentId" @change="sectionIds=[];shiftId='';syncShift()" required class="{{$input}}"><option value="">Choose</option><template x-for="dept in departments" :key="dept.id"><option :value="String(dept.id)" x-text="dept.name"></option></template></select></div>
                <div><label class="{{$label}}">Routine name</label><input name="name" value="{{old('name')}}" placeholder="11 Science Routine" required class="{{$input}}"></div>
                <template x-if="department?.academic_system==='semester'"><div><label class="{{$label}}">Semester</label><select name="semester" class="{{$input}}">@for($i=1;$i<=8;$i++)<option value="{{$i}}">Semester {{$i}}</option>@endfor</select></div></template>
                <template x-if="department?.academic_system==='year'"><div><label class="{{$label}}">Study year</label><select name="year_level" class="{{$input}}">@for($i=1;$i<=6;$i++)<option value="{{$i}}">Year {{$i}}</option>@endfor</select></div></template>
            </div>
            <div class="mt-3"><p class="{{$label}}">Section</p><div class="flex flex-wrap gap-2"><template x-for="section in sections" :key="section.id"><label :class="sectionIds.includes(String(section.id))?'border-emerald-600 bg-emerald-600 text-white':'border-gray-200 bg-gray-50 text-gray-600'" class="cursor-pointer rounded-lg border px-3 py-2 text-xs font-black"><input type="checkbox" name="section_ids[]" :value="section.id" x-model="sectionIds" class="sr-only"><span x-text="sectionIds.includes(String(section.id))?'✓ '+section.name:section.name"></span></label></template></div></div>
            <div class="mt-3 max-w-md"><label class="{{$label}}">Assigned time slot</label><select name="routine_shift_id" x-model="shiftId" required class="{{$input}}"><option value="">Choose</option><template x-for="shift in availableShifts" :key="shift.id"><option :value="String(shift.id)" x-text="shift.name+' · '+clock(shift.starts_at)+'–'+clock(shift.ends_at)"></option></template></select><p x-show="availableShifts.length===1" class="mt-1 text-[9px] font-bold text-emerald-700">✓ The only assigned time slot was selected automatically.</p><p x-show="departmentId&&!availableShifts.length" class="mt-1 text-[9px] font-bold text-amber-600">Assign a time slot first.</p></div>
            <div x-show="selectedShift" x-cloak class="mt-3 grid gap-3 rounded-xl border border-blue-100 bg-blue-50/50 p-3 lg:grid-cols-[.7fr_1.3fr]">
                <div><p class="{{$label}}">Days from time slot</p><div class="flex flex-wrap gap-1"><template x-for="day in selectedShift?.working_days||[]" :key="day"><span class="rounded-lg bg-white px-2.5 py-1.5 text-[10px] font-black text-blue-700" x-text="day.slice(0,3)"></span></template></div></div>
                <div><p class="{{$label}}">Periods you will schedule</p><div class="flex flex-wrap gap-1"><template x-for="period in selectedShift?.periods||[]" :key="period.id"><span :class="period.is_break?'bg-amber-100 text-amber-700':'bg-white text-gray-700'" class="rounded-lg px-2 py-1.5 text-[9px] font-black"><span x-text="period.name"></span><span class="ml-1 opacity-60" x-text="clock(period.starts_at)+'–'+clock(period.ends_at)"></span></span></template></div><p class="mt-2 text-[9px] font-bold text-blue-700">After opening the grid, click a period to choose its subject, teacher and room. Conflicts are checked before saving.</p></div>
            </div>
            <div class="mt-4 flex justify-end"><button :disabled="!yearId||!orgId||!departmentId||!shiftId||!sectionIds.length" class="rounded-lg bg-[#1a5632] px-5 py-2.5 text-xs font-black text-white disabled:opacity-40">Open days &amp; periods →</button></div>
        </form>
    </section>

    <div class="grid gap-4 xl:grid-cols-[1fr_20rem]"><section class="overflow-hidden rounded-2xl border bg-white shadow-sm"><header class="flex items-center justify-between border-b px-4 py-3"><div><h2 class="text-sm font-black">Saved routines</h2><p class="text-[10px] font-semibold text-gray-400">Draft routines stay editable; publishing locks the grid.</p></div><span class="rounded-full bg-gray-100 px-2.5 py-1 text-[10px] font-black text-gray-600">{{$plans->count()}}</span></header><div class="divide-y">@forelse($plans as $plan)<a href="{{route('admin.teaching-learning.routine-builder.show',$plan)}}" class="flex items-center justify-between gap-3 px-4 py-3 hover:bg-gray-50"><div class="min-w-0"><div class="flex items-center gap-2"><p class="truncate text-sm font-black">{{$plan->name}}</p><span class="rounded-md px-2 py-0.5 text-[9px] font-black {{$plan->status==='published'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}}">{{strtoupper($plan->status)}}</span></div><p class="mt-1 text-[10px] font-semibold text-gray-400">{{$plan->academicYear->name}} · {{$plan->organization->name}} · {{$plan->department->name}} · {{$plan->sections->pluck('name')->implode(', ')}}</p></div><div class="shrink-0 text-right"><p class="text-xs font-black text-[#1a5632]">{{$plan->lessons_count}} classes</p><p class="text-[9px] font-semibold text-gray-400">{{$plan->shift->name}}</p></div></a>@empty<div class="py-12 text-center text-sm font-bold text-gray-400">No routine workspaces yet.</div>@endforelse</div></section>
        <section class="rounded-2xl border bg-white p-4 shadow-sm"><div><p class="text-[10px] font-black uppercase tracking-wider text-purple-600">Room master</p><h2 class="text-sm font-black">Classrooms & laboratories</h2></div><form method="POST" action="{{route('admin.teaching-learning.routine-builder.rooms.store')}}" class="mt-3 space-y-2">@csrf<select name="organization_id" required class="{{$input}}"><option value="">Organization</option>@foreach($organizations as $org)<option value="{{$org->id}}">{{$org->name}}</option>@endforeach</select><div class="grid grid-cols-2 gap-2"><input name="name" required placeholder="Physics Lab" class="{{$input}}"><input name="code" required placeholder="PHY-LAB" class="{{$input}}"></div><div class="grid grid-cols-2 gap-2"><select name="type" class="{{$input}}"><option value="laboratory">Laboratory</option><option value="classroom">Classroom</option><option value="hall">Hall</option></select><input type="number" name="capacity" min="1" placeholder="Capacity" class="{{$input}}"></div><button class="w-full rounded-lg bg-purple-600 px-3 py-2 text-xs font-black text-white">+ Add room</button></form><div class="mt-3 max-h-52 divide-y overflow-auto">@forelse($rooms as $room)<div class="flex items-center justify-between py-2"><span><b class="block text-xs">{{$room->code}}</b><small class="text-[9px] text-gray-400">{{$room->name}} · {{$room->organization->name}}</small></span><span class="rounded bg-purple-50 px-1.5 py-1 text-[8px] font-black uppercase text-purple-700">{{$room->type}}</span></div>@empty<p class="py-4 text-center text-[10px] font-semibold text-gray-400">Add labs before practical scheduling.</p>@endforelse</div></section>
    </div>
</div>
@endsection
@push('scripts')<script>function planCreator(orgs,shifts){return{createOpen:@js($errors->any()),yearId:@js((string)old('academic_year_id',($academicYears->firstWhere('is_active',true)??$academicYears->first())?->id)),orgId:@js((string)old('organization_id','')),departmentId:@js((string)old('department_id','')),shiftId:@js((string)old('routine_shift_id','')),sectionIds:@js(collect(old('section_ids',[]))->map(fn($id)=>(string)$id)->values()),orgs,shifts,init(){this.syncShift()},get organization(){return this.orgs.find(o=>String(o.id)===this.orgId)},get departments(){return this.organization?.departments||[]},get department(){return this.departments.find(d=>String(d.id)===this.departmentId)},get sections(){return this.department?.sections||[]},get availableShifts(){if(!this.yearId||!this.orgId||!this.departmentId)return[];return this.shifts.filter(s=>(s.assignments||[]).some(a=>String(a.academic_year_id)===this.yearId&&String(a.organization_id)===this.orgId&&(a.department_id===null||String(a.department_id)===this.departmentId)))},get selectedShift(){return this.availableShifts.find(s=>String(s.id)===this.shiftId)},syncShift(){this.$nextTick(()=>{const choices=this.availableShifts;if(choices.length===1)this.shiftId=String(choices[0].id);else if(!choices.some(shift=>String(shift.id)===this.shiftId))this.shiftId=''})},clock(v){if(!v)return'';const [h,m]=v.slice(0,5).split(':').map(Number);return`${h%12||12}:${String(m).padStart(2,'0')} ${h<12?'AM':'PM'}`}}}</script>@endpush
