@extends('teaching_learning.layouts.app')
@section('title',$routinePlan->name)
@section('content')
@php
    $periods = $routinePlan->shift->periods;
    $dayLessons = $routinePlan->lessons->where('day_of_week', $day);
    $allowPeriodRange = $routinePlan->organization->type !== 'school';
@endphp
<div class="space-y-4" x-data="routineEditor(@js($entries),@js($offeringOptions),@js($teachers),@js($rooms),@js($periods),@js($day),@js($allowPeriodRange))">
    <section class="flex flex-col gap-3 rounded-2xl bg-gradient-to-r from-[#0b2415] to-[#1a5632] p-5 text-white lg:flex-row lg:items-center lg:justify-between">
        <div><div class="flex flex-wrap items-center gap-2"><span class="rounded-md bg-white/10 px-2 py-1 text-[9px] font-black uppercase">{{$routinePlan->academicYear->name}}</span><span class="rounded-md px-2 py-1 text-[9px] font-black uppercase {{$routinePlan->status==='published'?'bg-emerald-400/20 text-emerald-200':'bg-amber-400/20 text-amber-200'}}">{{$routinePlan->status}}</span></div><h1 class="mt-2 text-2xl font-black">{{$routinePlan->name}}</h1><p class="mt-1 text-xs font-semibold text-white/65">{{$routinePlan->organization->name}} · {{$routinePlan->department->name}} · {{$routinePlan->shift->name}} · {{$routinePlan->sections->count()}} sections</p></div>
        <div class="flex flex-wrap gap-2"><a href="{{route('admin.teaching-learning.routine-builder.index')}}" class="rounded-xl border border-white/20 bg-white/10 px-3 py-2.5 text-xs font-black">All routines</a><a href="{{route('admin.teaching-learning.routine-builder.print',$routinePlan)}}" target="_blank" class="rounded-xl border border-white/20 bg-white/10 px-3 py-2.5 text-xs font-black">Print final</a><form method="POST" action="{{route('admin.teaching-learning.routine-builder.publish',$routinePlan)}}">@csrf<button class="rounded-xl bg-white px-4 py-2.5 text-xs font-black text-[#1a5632]">{{$routinePlan->status==='published'?'Unlock draft':'Publish & lock'}}</button></form></div>
    </section>
    @if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-3 text-xs font-bold text-red-700">@foreach($errors->all() as $error)<p>• {{$error}}</p>@endforeach</div>@endif

    <section class="rounded-2xl border bg-white p-3 shadow-sm"><div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div class="flex flex-wrap gap-1">@foreach($routinePlan->shift->working_days as $workingDay)<a href="{{route('admin.teaching-learning.routine-builder.show',[$routinePlan,'day'=>$workingDay])}}" class="rounded-lg px-3 py-2 text-xs font-black {{$day===$workingDay?'bg-[#1a5632] text-white':'bg-gray-100 text-gray-600 hover:bg-gray-200'}}">{{substr($workingDay,0,3)}}</a>@endforeach</div><div class="flex flex-wrap items-center gap-3 text-[9px] font-bold text-gray-500"><span><i class="mr-1 inline-block h-2.5 w-2.5 rounded bg-emerald-100"></i>Theory · whole class</span><span><i class="mr-1 inline-block h-2.5 w-2.5 rounded bg-purple-100"></i>Practical · 50/50</span><span>{{$allowPeriodRange?'Bachelor: start and end periods allowed':'School: one period per class'}}</span></div></div></section>

    <section class="overflow-hidden rounded-2xl border bg-white shadow-sm">
        <header class="flex items-center justify-between border-b px-4 py-3"><div><p class="text-[10px] font-black uppercase tracking-wider text-[#1a5632]">Section / {{$day}}</p><h2 class="text-sm font-black">Routine grid</h2></div><p class="text-[10px] font-semibold text-gray-400">{{$routinePlan->is_locked?'Published routine — unlock to edit':'Choose a day, then click the starting period'}}</p></header>
        <div class="overflow-x-auto"><table class="w-full min-w-[980px] border-collapse text-center">
            <thead><tr class="bg-gray-50"><th class="sticky left-0 z-20 w-32 border-b border-r bg-gray-50 px-2 py-3 text-left text-[9px] font-black uppercase text-gray-500">Section / Group</th>@foreach($periods as $period)<th class="min-w-[118px] border-b border-r px-2 py-2 {{$period->is_break?'w-16 min-w-[64px] bg-amber-50':''}}"><span class="block text-[10px] font-black {{$period->is_break?'text-amber-700':'text-gray-800'}}">{{$period->name}}</span><span class="mt-0.5 block text-[8px] font-bold text-gray-400">{{date('g:i A',strtotime($period->starts_at))}}–{{date('g:i A',strtotime($period->ends_at))}}</span></th>@endforeach</tr></thead>
            <tbody>
            @foreach($routinePlan->sections as $section)
                <tr><th class="sticky left-0 z-10 border-b border-r bg-white px-2 py-3 text-left"><span class="block text-xs font-black">{{$section->name}}</span><span class="block text-[8px] font-bold uppercase text-gray-400">{{$section->group_name?:$routinePlan->department->name}}</span></th>
                @foreach($periods as $period)
                    @if($period->is_break)<td class="border-b border-r bg-amber-50/70 px-1 text-[9px] font-black uppercase tracking-widest text-amber-700">Break</td>
                    @else
                        @php $key=$section->id.':'.$period->id;$lesson=$cellLessons->get($key);$isStart=$lesson&&(int)$lesson->routine_period_id===(int)$period->id;$subject=$lesson?->groups->first()?->offering?->subject; @endphp
                        <td class="h-[76px] border-b border-r p-1">
                            @if($routinePlan->is_locked)
                                <div class="flex h-full flex-col justify-center rounded-lg {{$lesson?->mode==='practical_split'?'bg-purple-50':($lesson?'bg-emerald-50':'')}}">
                                    @if($lesson && $isStart)@foreach($lesson->groups as $group)<div class="px-1 py-0.5 {{$loop->first?'':'border-t border-purple-100'}}"><b class="block text-[10px] leading-tight">{{$lesson->mode==='practical_split'&&$subject->practical_code?$subject->practical_code:$subject->code}}</b><span class="text-[8px] font-bold text-gray-500">{{$group->teacher_initials}}{{$group->room?' · '.$group->room->code:''}}{{$lesson->mode==='practical_split'?' · 50%':''}}</span></div>@endforeach @elseif($lesson)<span class="text-[9px] font-black text-gray-500">↳ {{$subject?->code}} continues</span>@else<span class="text-gray-300">—</span>@endif
                                </div>
                            @else
                                <button type="button" @click="openCell(@js((string)$section->id),@js((string)$period->id),@js($section->name),@js($period->name))" class="flex h-full w-full flex-col justify-center rounded-lg border border-dashed transition {{$lesson?->mode==='practical_split'?'border-purple-200 bg-purple-50 hover:bg-purple-100':($lesson?'border-emerald-200 bg-emerald-50 hover:bg-emerald-100':'border-gray-200 text-gray-300 hover:border-emerald-300 hover:bg-emerald-50')}}">
                                    @if($lesson && $isStart)@foreach($lesson->groups as $group)<span class="w-full px-1 py-0.5 {{$loop->first?'':'border-t border-purple-100'}}"><b class="block text-[10px] leading-tight text-gray-900">{{$lesson->mode==='practical_split'&&$subject->practical_code?$subject->practical_code:$subject->code}}</b><small class="text-[8px] font-bold text-gray-500">{{$group->teacher_initials}}{{$group->room?' · '.$group->room->code:''}}{{$lesson->mode==='practical_split'?' · 50%':''}}</small></span>@endforeach @elseif($lesson)<span class="text-[9px] font-black text-gray-500">↳ {{$subject?->code}} continues</span>@else<span class="text-lg leading-none">+</span><small class="text-[8px] font-black">ADD</small>@endif
                                </button>
                            @endif
                        </td>
                    @endif
                @endforeach
                </tr>
            @endforeach
            </tbody>
        </table></div>
    </section>

    @php $splitLessons=$dayLessons->where('mode','practical_split'); @endphp
    @if($splitLessons->isNotEmpty())<section class="rounded-2xl border bg-white p-4 shadow-sm"><div class="mb-3"><p class="text-[10px] font-black uppercase tracking-wider text-purple-600">Automatically balanced</p><h2 class="text-sm font-black">{{$day}} practical group rosters</h2></div><div class="grid gap-2 lg:grid-cols-2">@foreach($splitLessons as $lesson)<details class="rounded-xl border border-purple-100 bg-purple-50/40 p-3"><summary class="cursor-pointer text-xs font-black">{{$lesson->section->name}} · {{$lesson->period->name}}{{$lesson->endPeriod&&$lesson->endPeriod->id!==$lesson->period->id?'–'.$lesson->endPeriod->name:''}} <span class="text-purple-600">({{$lesson->groups->sum(fn($group)=>$group->students->count())}} students)</span></summary><div class="mt-3 grid gap-2 sm:grid-cols-2">@foreach($lesson->groups as $group)<div class="rounded-lg bg-white p-2"><p class="text-[10px] font-black text-purple-700">{{$group->group_label}} · {{$group->offering->subject->practical_code?:$group->offering->subject->code}} · {{$group->teacher_initials}} · {{$group->room?->code}}</p><p class="mt-1 text-[9px] leading-4 text-gray-500">{{$group->students->map(fn($student)=>($student->roll_number?$student->roll_number.' · ':'').$student->full_name)->implode(', ')?:'No enrolled students found'}}</p></div>@endforeach</div></details>@endforeach</div></section>@endif

    @unless($routinePlan->is_locked)
    <dialog x-ref="editor" class="m-auto w-[calc(100%_-_2rem)] max-w-3xl rounded-2xl p-0 shadow-2xl backdrop:bg-gray-950/60">
        <form method="POST" action="{{route('admin.teaching-learning.routine-builder.lessons.save',$routinePlan)}}">@csrf @method('PUT')
            <input type="hidden" name="section_id" :value="sectionId"><input type="hidden" name="routine_period_id" :value="periodId"><input type="hidden" name="day_of_week" :value="day">
            <header class="flex items-center justify-between border-b px-5 py-4"><div><p class="text-[9px] font-black uppercase tracking-widest text-[#1a5632]" x-text="day+' · '+periodName"></p><h3 class="text-lg font-black" x-text="sectionName"></h3></div><button type="button" @click="$refs.editor.close()" class="h-8 w-8 rounded-full bg-gray-100 text-xl">×</button></header>
            <div class="space-y-4 p-5">
                <div class="grid gap-3 sm:grid-cols-2">
                    <div><label class="text-[9px] font-black uppercase text-gray-500">Subject for this faculty / section</label><select name="subject_offering_id" x-model="subjectOfferingId" @change="if(mode==='practical_split'&&!canPractical)setMode('single')" required class="mt-1 w-full rounded-lg border-gray-200 px-3 py-2 text-xs font-semibold"><option value="">Choose subject</option><template x-for="subject in subjectsForSection" :key="subject.id"><option :value="String(subject.id)" x-text="subject.code+' · '+subject.name+(subject.is_elective?' · Elective':'')"></option></template></select><p class="mt-1 text-[9px] font-semibold leading-4 text-gray-400">Compulsory subjects appear automatically. Electives appear only after students in this section are assigned.</p></div>
                    <div><label class="text-[9px] font-black uppercase text-gray-500">Period duration</label><div class="mt-1 flex items-center gap-2"><span class="flex-1 rounded-lg border bg-gray-50 px-3 py-2 text-xs font-black" x-text="startPeriod?.name"></span><span x-show="allowPeriodRange" class="text-gray-400">to</span><select x-show="allowPeriodRange" name="end_routine_period_id" x-model="endPeriodId" class="flex-1 rounded-lg border-gray-200 px-3 py-2 text-xs font-semibold"><template x-for="period in availableEndPeriods" :key="period.id"><option :value="String(period.id)" x-text="period.name+' · '+clock(period.ends_at)"></option></template></select><input x-show="!allowPeriodRange" type="hidden" name="end_routine_period_id" :value="periodId"></div><p class="mt-1 text-[9px] font-semibold text-gray-400" x-text="allowPeriodRange?'Bachelor classes may combine consecutive periods without crossing a break.':'School classes use exactly one period.'"></p></div>
                </div>
                <div class="grid grid-cols-2 gap-2"><label :class="mode==='single'?'border-emerald-600 bg-emerald-50 text-emerald-800':'border-gray-200'" class="cursor-pointer rounded-xl border p-3"><input type="radio" name="mode" value="single" x-model="mode" @change="setMode('single')" class="sr-only"><b class="block text-sm">Theory ✓</b><span class="text-[10px] text-gray-500">Whole class studies together</span></label><label @click.prevent="if(canPractical)setMode('practical_split')" :class="mode==='practical_split'?'border-purple-600 bg-purple-50 text-purple-800':(canPractical?'border-gray-200':'cursor-not-allowed border-gray-100 bg-gray-50 opacity-50')" class="cursor-pointer rounded-xl border p-3"><input type="radio" name="mode" value="practical_split" x-model="mode" class="sr-only"><b class="block text-sm">Practical ✓</b><span class="text-[10px] text-gray-500" x-text="canPractical?'Half in Lab A, half in Lab B':'Selected subject has no practical'"></span></label></div>
                <template x-for="(group,index) in groups" :key="index"><section :class="mode==='practical_split'?'border-purple-200 bg-purple-50/50':'border-emerald-200 bg-emerald-50/40'" class="rounded-xl border p-3"><div class="mb-2 flex items-center justify-between"><b class="text-xs" x-text="mode==='practical_split'?'Group '+String.fromCharCode(65+index)+' · 50% students':'Whole class · 100% students'"></b><span class="rounded bg-white px-2 py-1 text-[9px] font-black" x-text="mode==='practical_split'?'PARALLEL LAB':'THEORY'"></span></div><div class="grid gap-3 sm:grid-cols-[1fr_12rem]"><details class="rounded-lg border bg-white"><summary class="cursor-pointer px-3 py-2 text-xs font-black" x-text="group.teacher_ids.length?group.teacher_ids.length+' teacher(s) selected':'Choose teacher(s)'"></summary><div class="grid max-h-44 gap-1 overflow-auto border-t p-2 sm:grid-cols-2"><template x-for="teacher in teachers" :key="teacher.id"><label :class="group.teacher_ids.includes(String(teacher.id))?'bg-emerald-100 text-emerald-800':'bg-gray-50 text-gray-600'" class="flex cursor-pointer items-center gap-2 rounded-lg px-2 py-1.5 text-[10px] font-bold"><input type="checkbox" :name="`groups[${index}][teacher_ids][]`" :value="teacher.id" x-model="group.teacher_ids" class="rounded text-[#1a5632]"><span x-text="teacher.initials+' · '+teacher.name"></span></label></template></div></details><div><select :name="`groups[${index}][routine_room_id]`" x-model="group.routine_room_id" :required="mode==='practical_split'" class="w-full rounded-lg border-gray-200 px-2.5 py-2 text-xs font-semibold"><option value="" x-text="mode==='practical_split'?'Choose laboratory':'Optional room'"></option><template x-for="room in rooms" :key="room.id"><option :value="String(room.id)" x-text="room.code+' · '+room.name"></option></template></select></div></div><input type="hidden" :name="`groups[${index}][group_label]`" :value="mode==='practical_split'?'Group '+String.fromCharCode(65+index):''"></section></template>
                <div><label class="text-[9px] font-black uppercase text-gray-500">Note</label><input name="notes" x-model="notes" placeholder="Optional routine note" class="mt-1 w-full rounded-lg border-gray-200 px-3 py-2 text-xs"></div>
                <div class="rounded-xl bg-amber-50 p-3 text-[10px] font-bold text-amber-700">Before saving, the system checks every selected teacher, laboratory, section, day and the complete start-to-end time range.</div>
            </div>
            <footer class="flex items-center justify-between border-t px-5 py-4"><button x-show="hasEntry" name="intent" value="delete" class="rounded-lg border border-red-200 px-4 py-2 text-xs font-black text-red-600" onclick="return confirm('Clear this routine class?')">Clear class</button><span x-show="!hasEntry"></span><div class="flex gap-2"><button type="button" @click="$refs.editor.close()" class="rounded-lg border px-4 py-2 text-xs font-bold">Cancel</button><button name="intent" value="save" class="rounded-lg bg-[#1a5632] px-5 py-2 text-xs font-black text-white">Save &amp; check conflicts</button></div></footer>
        </form>
    </dialog>
    @endunless
</div>
@endsection
@push('scripts')
<script>
function routineEditor(entries,offerings,teachers,rooms,periods,day,allowPeriodRange){return{
    entries,offerings,teachers,rooms,periods,day,allowPeriodRange,sectionId:'',periodId:'',endPeriodId:'',sectionName:'',periodName:'',subjectOfferingId:'',mode:'single',notes:'',groups:[],hasEntry:false,
    blank(){return{teacher_ids:[],routine_room_id:'',group_label:''}},
    get subjectsForSection(){return this.offerings.filter(subject=>subject.section_ids.map(String).includes(String(this.sectionId)))},
    get selectedSubject(){return this.offerings.find(subject=>String(subject.id)===String(this.subjectOfferingId))},
    get canPractical(){return !!this.selectedSubject?.has_practical},
    get startPeriod(){return this.periods.find(period=>String(period.id)===String(this.periodId))},
    get availableEndPeriods(){const start=this.startPeriod;if(!start)return[];const result=[];for(const period of this.periods){if(period.position<start.position)continue;if(period.is_break){if(period.position>start.position)break;continue}result.push(period)}return result},
    openCell(sectionId,clickedPeriodId,sectionName,periodName){const entry=this.entries[`${sectionId}:${clickedPeriodId}`];this.sectionId=sectionId;this.periodId=entry?.routine_period_id||clickedPeriodId;this.endPeriodId=entry?.end_routine_period_id||this.periodId;this.sectionName=sectionName;this.periodName=this.periods.find(period=>String(period.id)===String(this.periodId))?.name||periodName;this.hasEntry=!!entry;this.subjectOfferingId=entry?.subject_offering_id||'';this.mode=entry?.mode||'single';this.notes=entry?.notes||'';this.groups=entry?JSON.parse(JSON.stringify(entry.groups)):[this.blank()];this.groups.forEach(group=>group.teacher_ids=(group.teacher_ids||[]).map(String));this.setMode(this.mode,true);this.$refs.editor.showModal()},
    setMode(mode,preserve=false){if(mode==='practical_split'&&!this.canPractical)return;this.mode=mode;if(mode==='single'){this.groups=[preserve&&this.groups[0]?this.groups[0]:this.groups[0]||this.blank()]}else{this.groups=[this.groups[0]||this.blank(),preserve&&this.groups[1]?this.groups[1]:this.groups[1]||this.blank()]}},
    clock(value){if(!value)return'';const [hour,minute]=value.slice(0,5).split(':').map(Number);return`${hour%12||12}:${String(minute).padStart(2,'0')} ${hour<12?'AM':'PM'}`}
}}
</script>
@endpush
