<header class="flex flex-col gap-2 border-b px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-sm font-black">Unique subject marks configuration</h2><p class="text-[10px] font-semibold text-gray-400">Enter each subject’s FM/PM once. The values apply automatically to every participating faculty/class.</p></div><div class="flex items-center gap-2"><span class="rounded-full bg-purple-50 px-2.5 py-1 text-[10px] font-black text-purple-700">{{$subjectRows->count()}} unique subjects</span>@if($canManage)<button type="button" onclick="document.getElementById('exam-details').showModal()" class="rounded-lg border px-3 py-1.5 text-[10px] font-black text-[#1a5632]">Exam setup</button>@endif</div></header>

@if($canManage && !$examination->is_locked)
<form method="POST" action="{{route('admin.examinations.subjects.update',$examination)}}">@csrf @method('PUT')
<div class="overflow-x-auto"><table class="min-w-full divide-y text-xs"><thead class="bg-gray-50 text-[9px] font-black uppercase text-gray-500"><tr><th class="w-12 px-3 py-2">Use</th><th class="min-w-48 px-3 py-2 text-left">Subject</th><th class="px-3 py-2 text-left">Used by</th><th class="w-20 px-3 py-2">TH FM</th><th class="w-20 px-3 py-2">TH PM</th><th class="w-24 px-3 py-2">PR code</th><th class="w-20 px-3 py-2">PR FM</th><th class="w-20 px-3 py-2">PR PM</th><th class="min-w-52 px-3 py-2 text-left">Routine teachers</th><th class="min-w-40 px-3 py-2 text-right">Marks</th></tr></thead><tbody class="divide-y">
@forelse($subjectRows as $row)@php $subject=$row['subject'];$sets=$row['configured'];$set=$sets->first();$practical=$subject->has_practical;$practicalCode=$subject->practical_code?:$subject->code; @endphp
<tr x-data="{enabled:@js($sets->isNotEmpty())}" :class="enabled?'bg-white':'bg-gray-50/70 text-gray-400'">
<td class="px-3 py-2 text-center"><input type="hidden" name="subjects[{{$subject->id}}][enabled]" value="0"><input type="checkbox" name="subjects[{{$subject->id}}][enabled]" value="1" x-model="enabled" class="rounded text-[#1a5632]"></td>
<td class="px-3 py-2"><p class="font-black text-gray-900">{{$subject->name}}</p><p class="text-[9px] font-bold text-emerald-700">TH {{$subject->code}}{{$row['is_elective']?' · ELECTIVE':''}}</p></td>
<td class="px-3 py-2"><div class="flex flex-wrap gap-1">@foreach($row['offerings']->pluck('department.name')->unique() as $faculty)<span class="rounded bg-gray-100 px-1.5 py-0.5 text-[9px] font-bold text-gray-600">{{$faculty}}</span>@endforeach</div></td>
@foreach(['theory_full_marks'=>$practical?75:100,'theory_pass_marks'=>$practical?30:40] as $field=>$default)<td class="px-3 py-2"><input type="number" step="0.01" min="0" name="subjects[{{$subject->id}}][{{$field}}]" value="{{$set?->{$field}??$default}}" :disabled="!enabled" class="w-16 rounded-lg border-gray-200 px-1.5 py-1.5 text-center text-xs font-black"></td>@endforeach
<td class="px-3 py-2 text-center font-black {{$practical?'text-purple-700':'text-gray-300'}}">{{$practical?$practicalCode:'—'}}</td>
@foreach(['practical_full_marks'=>25,'practical_pass_marks'=>10] as $field=>$default)<td class="px-3 py-2">@if($practical)<input type="number" step="0.01" min="0" name="subjects[{{$subject->id}}][{{$field}}]" value="{{$set?->{$field}??$default}}" :disabled="!enabled" class="w-16 rounded-lg border-gray-200 px-1.5 py-1.5 text-center text-xs font-black">@else<span class="block text-center text-gray-300">—</span>@endif</td>@endforeach
<td class="px-3 py-2"><p class="text-[9px] font-bold text-emerald-700">TH: {{$row['theory_labels']->implode(', ')?:'Not assigned'}}</p>@if($practical)<p class="mt-1 text-[9px] font-bold text-purple-700">PR: {{$row['practical_labels']->implode(', ')?:'Not assigned'}}</p>@endif</td>
<td class="px-3 py-2"><div class="flex flex-wrap justify-end gap-1">@foreach($sets as $examSubject)@php $access=$markAccess->get($examSubject->id,['theory'=>0,'practical'=>0]);$faculty=$examSubject->offering->department->name; @endphp @if($access['theory'])<a title="{{$faculty}}" href="{{route('admin.examinations.marks.edit',[$examSubject,'component'=>'theory'])}}" class="rounded bg-emerald-600 px-2 py-1 text-[9px] font-black text-white">TH {{$faculty}}</a>@endif @if($access['practical'])<a title="{{$faculty}}" href="{{route('admin.examinations.marks.edit',[$examSubject,'component'=>'practical'])}}" class="rounded bg-purple-600 px-2 py-1 text-[9px] font-black text-white">PR {{$faculty}}</a>@endif @endforeach @if($sets->isEmpty())<span class="text-[9px] font-bold text-gray-300">Save first</span>@endif</div></td>
</tr>
@empty<tr><td colspan="10" class="p-8 text-center text-sm font-bold text-gray-400">No curriculum subjects found.</td></tr>@endforelse
</tbody></table></div><div class="sticky bottom-0 flex items-center justify-between border-t bg-white/95 px-4 py-3"><p class="text-[10px] font-semibold text-gray-400">One subject row updates all its class/faculty offerings.</p><button class="rounded-lg bg-[#1a5632] px-5 py-2.5 text-xs font-black text-white">Save unique FM / PM</button></div></form>
@else
<div class="divide-y">@foreach($subjectRows as $row)@php $visible=$row['configured']->filter(fn($set)=>(($markAccess->get($set->id)['theory']??0)||($markAccess->get($set->id)['practical']??0))); @endphp @if($visible->isNotEmpty())<div class="flex items-center justify-between gap-3 px-4 py-3"><div><p class="text-sm font-black">{{$row['subject']->name}}</p><p class="text-[10px] font-bold text-gray-400">TH {{$row['subject']->code}}@if($row['subject']->has_practical) · PR {{$row['subject']->practical_code?:$row['subject']->code}}@endif</p></div><div class="flex flex-wrap justify-end gap-1">@foreach($visible as $set)@php $access=$markAccess->get($set->id); @endphp @if($access['theory'])<a href="{{route('admin.examinations.marks.edit',[$set,'component'=>'theory'])}}" class="rounded bg-emerald-600 px-2.5 py-1.5 text-[10px] font-black text-white">TH · {{$set->offering->department->name}}</a>@endif @if($access['practical'])<a href="{{route('admin.examinations.marks.edit',[$set,'component'=>'practical'])}}" class="rounded bg-purple-600 px-2.5 py-1.5 text-[10px] font-black text-white">PR · {{$set->offering->department->name}}</a>@endif @endforeach</div></div>@endif @endforeach</div>
@endif
