<header class="flex flex-col gap-2 border-b px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-sm font-black">Subject marks configuration</h2><p class="text-[10px] font-semibold text-gray-400">Subjects come from the selected faculties. Enter FM/PM once, even when several faculties use the subject.</p></div><span class="self-start rounded-full bg-purple-50 px-2.5 py-1 text-[10px] font-black text-purple-700">{{$subjectRows->count()}} unique subjects</span></header>
@if($canManage && !$examination->is_locked)
<form method="POST" action="{{route('admin.examinations.subjects.update',$examination)}}" x-data="{saving:false}" @submit="saving=true">@csrf @method('PUT')
    <div class="divide-y divide-gray-100">
    @forelse($subjectRows as $row)
        @php $subject=$row['subject'];$sets=$row['configured'];$set=$sets->first();$practical=$subject->has_practical;$practicalCode=$subject->practical_code?:$subject->code; @endphp
        <article x-data="{enabled:@js($sets->isNotEmpty())}" :class="enabled?'border-l-4 border-emerald-500 bg-emerald-50/30':'border-l-4 border-transparent bg-gray-50/70'" class="grid gap-3 p-3 transition-all md:grid-cols-[minmax(12rem,1.4fr)_minmax(10rem,1fr)_auto_auto] md:items-center">
            <label class="flex min-w-0 cursor-pointer items-center gap-3"><input type="hidden" name="subjects[{{$subject->id}}][enabled]" value="0"><input type="checkbox" name="subjects[{{$subject->id}}][enabled]" value="1" x-model="enabled" class="sr-only"><span :class="enabled?'bg-emerald-600 text-white':'border border-gray-300 bg-white text-transparent'" class="grid h-7 w-7 shrink-0 place-items-center rounded-lg text-xs font-black">✓</span><span class="min-w-0"><b class="block truncate text-sm text-gray-900">{{$subject->name}}</b><small class="font-black text-emerald-700">TH {{$subject->code}}{{$row['is_elective']?' · ELECTIVE':''}}</small></span></label>
            <div><p class="mb-1 text-[8px] font-black uppercase text-gray-400">Used by</p><div class="flex flex-wrap gap-1">@foreach($row['offerings']->pluck('department.name')->unique() as $faculty)<span class="rounded border border-blue-100 bg-blue-50 px-1.5 py-1 text-[9px] font-bold text-blue-700">{{$faculty}}</span>@endforeach</div></div>
            <div class="grid grid-cols-2 gap-1.5 rounded-lg border border-emerald-200 bg-emerald-50 p-1.5"><label><span class="block text-center text-[8px] font-black text-emerald-700">TH FM</span><input type="number" step="0.01" min="0" name="subjects[{{$subject->id}}][theory_full_marks]" value="{{$set?->theory_full_marks??($practical?75:100)}}" :disabled="!enabled" class="w-full rounded-md border border-emerald-200 bg-white px-2 py-1.5 text-center text-xs font-black outline-none transition-colors duration-300 hover:border-emerald-300 focus:border-emerald-600 focus:ring-2 focus:ring-emerald-600/15 disabled:border-gray-100 disabled:text-gray-300 md:w-20"></label><label><span class="block text-center text-[8px] font-black text-emerald-700">TH PM</span><input type="number" step="0.01" min="0" name="subjects[{{$subject->id}}][theory_pass_marks]" value="{{$set?->theory_pass_marks??($practical?27:40)}}" :disabled="!enabled" class="w-full rounded-md border border-emerald-200 bg-white px-2 py-1.5 text-center text-xs font-black outline-none transition-colors duration-300 hover:border-emerald-300 focus:border-emerald-600 focus:ring-2 focus:ring-emerald-600/15 disabled:border-gray-100 disabled:text-gray-300 md:w-20"></label></div>
            <div class="flex items-end gap-2">@if($practical)<div class="grid w-full grid-cols-2 gap-1.5 rounded-lg border border-purple-200 bg-purple-50 p-1.5"><label><span class="block text-center text-[8px] font-black text-purple-600">PR FM · {{$practicalCode}}</span><input type="number" step="0.01" min="0" name="subjects[{{$subject->id}}][practical_full_marks]" value="{{$set?->practical_full_marks??25}}" :disabled="!enabled" class="w-full rounded-md border border-purple-200 bg-white px-2 py-1.5 text-center text-xs font-black outline-none transition-colors duration-300 hover:border-purple-300 focus:border-purple-600 focus:ring-2 focus:ring-purple-600/15 disabled:border-purple-100 disabled:text-gray-300 md:w-20"></label><label><span class="block text-center text-[8px] font-black text-purple-600">PR PM</span><input type="number" step="0.01" min="0" name="subjects[{{$subject->id}}][practical_pass_marks]" value="{{$set?->practical_pass_marks??10}}" :disabled="!enabled" class="w-full rounded-md border border-purple-200 bg-white px-2 py-1.5 text-center text-xs font-black outline-none transition-colors duration-300 hover:border-purple-300 focus:border-purple-600 focus:ring-2 focus:ring-purple-600/15 disabled:border-purple-100 disabled:text-gray-300 md:w-20"></label></div>@else<span class="rounded-lg border border-dashed border-gray-200 px-3 py-2 text-[9px] font-bold text-gray-300">No practical</span>@endif</div>
            <div class="md:col-start-2 md:col-end-5 md:-mt-2"><p class="text-[9px] font-semibold text-gray-400"><b class="text-emerald-700">Theory:</b> {{$row['theory_labels']->implode(', ')?:'Teacher follows published routine'}} @if($practical)<span class="mx-1">·</span><b class="text-purple-700">Practical:</b> {{$row['practical_labels']->implode(', ')?:'Teacher follows published routine'}}@endif</p>@if($sets->isNotEmpty())<div class="mt-1 flex flex-wrap gap-1">@foreach($sets as $examSubject)@php $access=$markAccess->get($examSubject->id,['theory'=>0,'practical'=>0]); @endphp @if($access['theory'])<a href="{{route('admin.examinations.marks.edit',[$examSubject,'component'=>'theory'])}}" class="rounded bg-emerald-600 px-2 py-1 text-[9px] font-black text-white">TH marks · {{$examSubject->offering->department->name}}</a>@endif @if($access['practical'])<a href="{{route('admin.examinations.marks.edit',[$examSubject,'component'=>'practical'])}}" class="rounded bg-purple-600 px-2 py-1 text-[9px] font-black text-white">PR marks · {{$examSubject->offering->department->name}}</a>@endif @endforeach</div>@endif</div>
        </article>
    @empty<div class="p-10 text-center"><p class="text-sm font-black text-gray-500">No faculty subjects found</p><p class="mt-1 text-xs font-semibold text-gray-400">Add subjects to the selected faculties first. Electives appear only after section/student assignment.</p></div>@endforelse
    </div>
    <footer class="sticky bottom-0 flex items-center justify-between gap-3 border-t bg-white/95 px-4 py-3 backdrop-blur"><p class="text-[10px] font-semibold text-gray-400">Fast save: student enrollment is not rebuilt.</p><button :disabled="saving" class="shrink-0 rounded-xl bg-[#1a5632] px-5 py-2.5 text-xs font-black text-white disabled:opacity-50"><span x-show="!saving">Save FM / PM</span><span x-show="saving" x-cloak>Saving…</span></button></footer>
</form>
@else
@if(!($markEntryOpen ?? false))<div class="border-b border-amber-200 bg-amber-50 px-4 py-3"><p class="text-xs font-black text-amber-800">Mark entry is not open</p><p class="mt-0.5 text-[10px] font-semibold text-amber-700">An examination manager must set this exam to <b>Ongoing</b>, and today's date must be inside the exam period.</p></div>@endif
@if($markEntryOpen ?? false)
<div class="divide-y">@forelse($subjectRows as $row)@php $visible=$row['configured']->filter(fn($set)=>(($markAccess->get($set->id)['theory']??0)||($markAccess->get($set->id)['practical']??0))); @endphp @if($visible->isNotEmpty())<div class="flex items-center justify-between gap-3 px-4 py-3"><div><p class="text-sm font-black">{{$row['subject']->name}}</p><p class="text-[10px] font-bold text-gray-400">TH {{$row['subject']->code}}@if($row['subject']->has_practical) · PR {{$row['subject']->practical_code?:$row['subject']->code}}@endif</p></div><div class="flex flex-wrap justify-end gap-1">@foreach($visible as $set)@php $access=$markAccess->get($set->id); @endphp @if($access['theory'])<a href="{{route('admin.examinations.marks.edit',[$set,'component'=>'theory'])}}" class="rounded bg-emerald-600 px-2.5 py-1.5 text-[10px] font-black text-white">TH · {{$set->offering->department->name}}</a>@endif @if($access['practical'])<a href="{{route('admin.examinations.marks.edit',[$set,'component'=>'practical'])}}" class="rounded bg-purple-600 px-2.5 py-1.5 text-[10px] font-black text-white">PR · {{$set->offering->department->name}}</a>@endif @endforeach</div></div>@endif @empty<p class="p-8 text-center text-sm font-bold text-gray-400">No subjects configured.</p>@endforelse</div>
@endif
@endif
